# -*- coding: utf-8 -*-
"""Capstone Project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17cwmfQloQarzYoJXJtG50XhfNvdKXaPR

# Capstone Project
## Image classifier for the SVHN dataset
### Instructions

In this notebook, you will create a neural network that classifies real-world images digits. You will use concepts from throughout this course in building, training, testing, validating and saving your Tensorflow classifier model.

This project is peer-assessed. Within this notebook you will find instructions in each section for how to complete the project. Pay close attention to the instructions as the peer review will be carried out according to a grading rubric that checks key parts of the project instructions. Feel free to add extra cells into the notebook as required.

### How to submit

When you have completed the Capstone project notebook, you will submit a pdf of the notebook for peer review. First ensure that the notebook has been fully executed from beginning to end, and all of the cell outputs are visible. This is important, as the grading rubric depends on the reviewer being able to view the outputs of your notebook. Save the notebook as a pdf (you could download the notebook with File -> Download .ipynb, open the notebook locally, and then File -> Download as -> PDF via LaTeX), and then submit this pdf for review.

### Let's get started!

We'll start by running some imports, and loading the dataset. For this project you are free to make further imports throughout the notebook as you wish.
"""

# Commented out IPython magic to ensure Python compatibility.
import tensorflow as tf
from scipy.io import loadmat
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets, model_selection
from sklearn.model_selection import train_test_split
# %matplotlib inline
from tqdm import tqdm
from tensorflow.keras import models
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Flatten
from tensorflow.keras.layers import Conv2D, MaxPooling2D, BatchNormalization
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.preprocessing import image
from tensorflow.keras.callbacks import ModelCheckpoint, EarlyStopping

"""For the capstone project, you will use the [SVHN dataset](http://ufldl.stanford.edu/housenumbers/). This is an image dataset of over 600,000 digit images in all, and is a harder dataset than MNIST as the numbers appear in the context of natural scene images. SVHN is obtained from house numbers in Google Street View images.

* Y. Netzer, T. Wang, A. Coates, A. Bissacco, B. Wu and A. Y. Ng. "Reading Digits in Natural Images with Unsupervised Feature Learning". NIPS Workshop on Deep Learning and Unsupervised Feature Learning, 2011.

The train and test datasets required for this project can be downloaded from [here](http://ufldl.stanford.edu/housenumbers/train.tar.gz) and [here](http://ufldl.stanford.edu/housenumbers/test.tar.gz). Once unzipped, you will have two files: `train_32x32.mat` and `test_32x32.mat`. You should store these files in Drive for use in this Colab notebook.

Your goal is to develop an end-to-end workflow for building, training, validating, evaluating and saving a neural network that classifies a real-world image into one of ten classes.
"""

# Run this cell to connect to your Drive folder

from google.colab import drive
drive.mount('/content/gdrive')

# Load the dataset from your Drive folder

train = loadmat('/content/drive/MyDrive/data/SVHN/train_32x32.mat')
test = loadmat('/content/drive/MyDrive/data/SVHN/test_32x32.mat')

"""Both `train` and `test` are dictionaries with keys `X` and `y` for the input images and labels respectively.

## 1. Inspect and preprocess the dataset
* Extract the training and testing images and labels separately from the train and test dictionaries loaded for you.
* Select a random sample of images and corresponding labels from the dataset (at least 10), and display them in a figure.
* Convert the training and test images to grayscale by taking the average across all colour channels for each pixel. _Hint: retain the channel dimension, which will now have size 1._
* Select a random sample of the grayscale images and corresponding labels from the dataset (at least 10), and display them in a figure.
"""

X_train, X_test, y_train, y_test = train['X'], test['X'], train['y'], test['y']
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

X_train = X_train.transpose(3,0,1,2)
X_test = X_test.transpose(3,0,1,2)
print(X_train.shape)
print(X_test.shape)

import random

n = X_train.shape[0]
row, col = 3, 4
fig = plt.figure()

for i in range(12):
    r = random.randint(0, n-1)
    image = X_train[r,:,:,:]
    plt.subplot(row,col,i+1)
    plt.tight_layout()
    plt.imshow(image)
    plt.title("label: {}".format(y_train[r,0]))

X_train = np.mean(X_train, axis = 3)
X_test = np.mean(X_test, axis = 3)
X_train = X_train[... , np.newaxis]
X_test = X_test[... , np.newaxis]
X_train.shape

n = X_train.shape[0]
row, col = 3, 4
fig = plt.figure()

for i in range(12):
    r = random.randint(0, n-1)
    image = X_train[r,:,:,0]
    plt.subplot(row,col,i+1)
    plt.tight_layout()
    plt.imshow(image)
    plt.title("label: {}".format(y_train[r,0]))

X_train = X_train/255
X_test  = X_test/255
y_test = y_test - 1
y_train = y_train - 1

"""## 2. MLP neural network classifier
* Build an MLP classifier model using the Sequential API. Your model should use only Flatten and Dense layers, with the final layer having a 10-way softmax output. 
* You should design and build the model yourself. Feel free to experiment with different MLP architectures. _Hint: to achieve a reasonable accuracy you won't need to use more than 4 or 5 layers._
* Print out the model summary (using the summary() method)
* Compile and train the model (we recommend a maximum of 30 epochs), making use of both training and validation sets during the training run. 
* Your model should track at least one appropriate metric, and use at least two callbacks during training, one of which should be a ModelCheckpoint callback.
* As a guide, you should aim to achieve a final categorical cross entropy training loss of less than 1.0 (the validation loss might be higher).
* Plot the learning curves for loss vs epoch and accuracy vs epoch for both training and validation sets.
* Compute and display the loss and accuracy of the trained model on the test set.
"""

model = Sequential([
    
    Flatten(input_shape = X_train[0].shape),
    Dense(64, activation = 'relu'),
    Dense(256, activation = 'relu'),
    Dense(128, activation = 'relu'),
    Dense(64, activation = 'relu'),
    Dense(10, activation = 'softmax')
])
model.summary()

model.compile(optimizer = 'adam',
              loss = 'sparse_categorical_crossentropy',
              metrics = ['accuracy']
)

from tensorflow.keras.callbacks import ModelCheckpoint, EarlyStopping

EarlyStop = EarlyStopping(patience = 6,
                         verbose = 1)
checkpoint_path = "svhn_dense/Dense_checkpoint"

model_checkpoint = ModelCheckpoint(filepath = checkpoint_path,
                                  save_weights_only = True,
                                  save_best_only = True,
                                  save_freq = 'epoch',
                                  verbose = 1)

history = model.fit(X_train, y_train,
                   validation_data = (X_test, y_test),
                    #validation_split = 0.15,
                   epochs = 30,
                    batch_size = 512,
                    callbacks = [EarlyStop, model_checkpoint],
                   verbose = 1)

import pandas as pd
df = pd.DataFrame(history.history)
import seaborn as sns

g = sns.lineplot(x = df.index, y ='loss', data = df, label = 'Training')
g = sns.lineplot(x = df.index, y ='val_loss', data = df, label = 'Validition')
g.set_title("loss vs epochs")
g.legend()

g = sns.lineplot(x = df.index, y ='accuracy', data = df, label = 'Training')
g = sns.lineplot(x = df.index, y ='val_accuracy', data = df, label = 'Validation')
g.set_title("accuracy vs epochs")
g.legend()

"""## 3. CNN neural network classifier
* Build a CNN classifier model using the Sequential API. Your model should use the Conv2D, MaxPool2D, BatchNormalization, Flatten, Dense and Dropout layers. The final layer should again have a 10-way softmax output. 
* You should design and build the model yourself. Feel free to experiment with different CNN architectures. _Hint: to achieve a reasonable accuracy you won't need to use more than 2 or 3 convolutional layers and 2 fully connected layers.)_
* The CNN model should use fewer trainable parameters than your MLP model.
* Compile and train the model (we recommend a maximum of 30 epochs), making use of both training and validation sets during the training run.
* Your model should track at least one appropriate metric, and use at least two callbacks during training, one of which should be a ModelCheckpoint callback.
* You should aim to beat the MLP model performance with fewer parameters!
* Plot the learning curves for loss vs epoch and accuracy vs epoch for both training and validation sets.
* Compute and display the loss and accuracy of the trained model on the test set.
"""

model_cnn = Sequential([
    Conv2D(32, (3,3),activation = 'relu', input_shape = X_train[0].shape),
    MaxPooling2D((2,2)),
    Dropout(.2),
    Conv2D(32, (3,3),activation = 'relu'),
    MaxPooling2D((2,2)),
    Dropout(.2),
    BatchNormalization(),
    
    Flatten(),
    Dropout(.2),
    Dense(16, activation = 'relu'),
    Dropout(.2),
    Dense(10, activation = 'softmax')
    
])
model_cnn.summary()

model_cnn.compile(optimizer = 'adam',
                 loss = 'sparse_categorical_crossentropy',
                 metrics =['accuracy'])

checkpoint_path = "svhn_dense/cnn_checkpoint"

modelcnn_checkpoint = ModelCheckpoint(filepath = checkpoint_path,
                                  save_weights_only = True,
                                  save_best_only = True,
                                  save_freq = 'epoch',
                                  verbose = 1)

history_cnn = model_cnn.fit(X_train, y_train, 
                            validation_data = (X_test, y_test),
                            callbacks = [EarlyStop, modelcnn_checkpoint],
                            epochs = 30, batch_size = 512,
                            verbose = 1 )

df_cnn = pd.DataFrame(history_cnn.history)
g = sns.lineplot(x = df_cnn.index, y ='loss', data = df_cnn, label = 'Training')
g = sns.lineplot(x = df_cnn.index, y ='val_loss', data = df_cnn, label = 'Validition')
g.set_title("loss vs epochs")
g.legend()

g = sns.lineplot(x = df_cnn.index, y ='accuracy', data = df_cnn, label = 'Training')
g = sns.lineplot(x = df_cnn.index, y ='val_accuracy', data = df_cnn, label = 'Validation')
g.set_title("accuracy vs epochs")
g.legend()

"""## 4. Get model predictions
* Load the best weights for the MLP and CNN models that you saved during the training run.
* Randomly select 5 images and corresponding labels from the test set and display the images with their labels.
* Alongside the image and label, show each model’s predictive distribution as a bar chart, and the final model prediction given by the label with maximum probability.
"""

model.load_weights("svhn_dense/Dense_checkpoint")
model_cnn.load_weights("svhn_dense/cnn_checkpoint")

n = X_test.shape[0]
row, col = 5, 3
fig = plt.figure(figsize = (16,12))
y = [1,2,3,4,5,6,7,8,9,10]
for i in range(5):
    r = random.randint(0, n-1)
    image = X_test[r,:,:,0]
    image_input = X_test[r]
    prediction_dense = model.predict(image_input[np.newaxis, ...])
    prediction_cnn = model_cnn.predict(image_input[np.newaxis, ...])

    plt.subplot(row,col,3*i+1)
    plt.tight_layout()
    plt.imshow(image)
    plt.title("label: {}".format(y_test[r,0] + 1))


    plt.subplot(row,col,3*i+2)
    plt.tight_layout()
    plt.bar(y, prediction_dense[0])
    plt.title("Dense Prediction: {}".format(tf.argmax(prediction_dense[0])+1))
    plt.xticks(y)

    plt.subplot(row,col,3*i+3)
    plt.tight_layout()
    plt.bar(y, prediction_cnn[0])
    plt.title("CNN prediction: {}".format(tf.argmax(prediction_cnn[0]) + 1))
    plt.xticks(y)

